-- ============================================================
-- Bug Tracker — Supabase schema (PostgreSQL)
-- Run this in the Supabase SQL editor (one project = one tracker).
-- ============================================================

-- --- Enums ---------------------------------------------------
do $$ begin
  create type bug_status as enum ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type bug_priority as enum ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type bug_type as enum (
    'BUG', 'UI_UX', 'PERFORMANCE', 'FEATURE_REQUEST', 'SECURITY', 'OTHER'
  );
exception when duplicate_object then null;
end $$;

do $$ begin
  create type bug_event_type as enum (
    'TICKET_CREATED', 'STATUS_CHANGED', 'PRIORITY_CHANGED',
    'TYPE_CHANGED', 'NOTE_ADDED', 'PUBLIC_REPLY_ADDED', 'PUBLIC_REPLY_DELETED'
  );
exception when duplicate_object then null;
end $$;
-- Added after initial deploy: keep existing installs compatible.
do $$ begin
  alter type bug_event_type add value if not exists 'PUBLIC_REPLY_ADDED';
exception when duplicate_object then null;
end $$;
do $$ begin
  alter type bug_event_type add value if not exists 'PUBLIC_REPLY_DELETED';
exception when duplicate_object then null;
end $$;

-- --- Main table ----------------------------------------------
create table if not exists public.bug_reports (
  id uuid primary key,
  ticket_number text unique not null,
  -- Long random token for the reporter's personal status link.
  -- Generated app-side (32 random bytes, hex).
  public_access_token text unique not null,

  title text not null check (char_length(title) between 5 and 150),
  description text not null check (char_length(description) between 20 and 5000),
  type bug_type not null default 'BUG',
  priority bug_priority not null default 'MEDIUM',
  status bug_status not null default 'OPEN',
  email text null check (email is null or email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  -- Application chosen by the reporter from NEXT_PUBLIC_APPS (null = n/a).
  app text null,

  browser text null,
  os text null,
  viewport text null,
  user_agent text null,
  language text null,
  source_url text null,

  screenshot_path text null,
  admin_notes text null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bug_reports_status_idx on public.bug_reports (status);
create index if not exists bug_reports_priority_idx on public.bug_reports (priority);
create index if not exists bug_reports_created_idx on public.bug_reports (created_at desc);
create index if not exists bug_reports_ticket_idx on public.bug_reports (ticket_number);
create index if not exists bug_reports_app_idx on public.bug_reports (app);

-- --- Ticket numbers --------------------------------------------
-- Generated by the app as random BUG-XXXX-XXXX codes (src/lib/ticket.ts),
-- unique thanks to the constraint on ticket_number. The old sequential
-- per-year counter made numbers guessable; drop it if it exists.
drop function if exists public.mint_ticket_number();
drop table if exists public.ticket_counters;

-- --- Audit / history ------------------------------------------
create table if not exists public.bug_events (
  id uuid primary key default gen_random_uuid(),
  bug_id uuid not null references public.bug_reports (id) on delete cascade,
  event_type bug_event_type not null,
  old_value text null,
  new_value text null,
  created_at timestamptz not null default now(),
  created_by uuid null
);

create index if not exists bug_events_bug_idx on public.bug_events (bug_id, created_at desc);

-- --- Public replies (admin -> reporter thread) -------------------
-- Visible ONLY via the personal status link (?token=), never via the
-- ticket-number lookup. Internal notes stay in bug_reports.admin_notes.
create table if not exists public.bug_comments (
  id uuid primary key default gen_random_uuid(),
  bug_id uuid not null references public.bug_reports (id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  -- ADMIN today; REPORTER reserved for a future token-based reply endpoint.
  author text not null default 'ADMIN' check (author in ('ADMIN', 'REPORTER')),
  created_at timestamptz not null default now(),
  created_by uuid null
);

create index if not exists bug_comments_bug_idx on public.bug_comments (bug_id, created_at asc);

-- --- updated_at trigger ----------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists bug_reports_touch on public.bug_reports;
create trigger bug_reports_touch
  before update on public.bug_reports
  for each row execute function public.touch_updated_at();

-- --- Row Level Security ----------------------------------------
alter table public.bug_reports enable row level security;
alter table public.bug_events enable row level security;
alter table public.bug_comments enable row level security;

-- Anonymous (public reporters): NO direct table access at all.
-- Reporters stay anonymous (no login) but create tickets only through
-- POST /api/bugs, which verifies Turnstile, rate-limits and validates,
-- then inserts with the service role. A direct anon INSERT policy would
-- let anyone with the public anon key skip all of that, so it is dropped.
drop policy if exists "anon_insert_reports" on public.bug_reports;

-- --- Admins -------------------------------------------------------
-- Being signed in is NOT enough: anyone can sign up through the public
-- anon key if sign-ups are enabled. Only users listed here get access.
-- After running this script, add yourself (SQL editor):
--   insert into public.admins (user_id)
--   select id from auth.users where email = 'you@example.com'
--   on conflict do nothing;
create table if not exists public.admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);
-- RLS on with no policies: only the SQL editor / service role can edit it.
alter table public.admins enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

-- Admins (listed in public.admins): full access.
drop policy if exists "auth_all_reports" on public.bug_reports;
create policy "auth_all_reports"
  on public.bug_reports for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "auth_all_events" on public.bug_events;
create policy "auth_all_events"
  on public.bug_events for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- Public replies: admins manage them; the public reads them only through
-- the service-role status API (anon has no direct access).
drop policy if exists "auth_all_comments" on public.bug_comments;
create policy "auth_all_comments"
  on public.bug_comments for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- Service-role bypasses RLS automatically: the public API routes
-- (/api/bugs, /api/status) use it server-side, so anon needs no policies.

-- --- Storage ----------------------------------------------------
-- Create a PRIVATE bucket named "screenshots" (Dashboard:
-- Storage -> New bucket -> Private). Then run:

-- Allow the server (service role bypasses RLS, so this is for completeness):
-- no public read. Admin downloads via signed URLs generated server-side.

-- The admin detail page creates signed URLs with the *authenticated user*
-- session (not service-role), so RLS must allow admins to read objects
-- in this bucket. Without this policy screenshots upload fine but never
-- display in the dashboard.
drop policy if exists "auth_read_screenshots" on storage.objects;
create policy "auth_read_screenshots"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'screenshots' and public.is_admin());

-- If you prefer managing storage policies in SQL:
-- insert into storage.buckets (id, name, public)
-- values ('screenshots', 'screenshots', false)
-- on conflict (id) do nothing;
